service: thumbgen-ai-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'ap-southeast-1'}
  memorySize: 512
  timeout: 29
  logRetentionInDays: 14
  environment:
    NODE_ENV: ${self:provider.stage}
    USERS_TABLE: ${ssm:/thumbgenai/users-table}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:TransactWriteItems
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${ssm:/thumbgenai/users-table}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${ssm:/thumbgenai/users-table}/index/email-index

package:
  patterns:
    - '!src/**'
    - '!test/**'
    - '!*.md'
    - '!*.mjs'
    - '!tsconfig*.json'
    - '!nest-cli.json'
    - 'dist/**'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: '*'
          path: /
      - httpApi:
          method: '*'
          path: /{proxy+}
