service: thumbgen-ai-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'ap-southeast-1'}
  memorySize: 512
  timeout: 29
  logRetentionInDays: 14
  environment:
    NODE_ENV: ${self:provider.stage}
    USERS_TABLE: ${ssm:/thumbgenai/users-table}
    SESSIONS_TABLE: ${ssm:/thumbgenai/sessions-table}
    THUMBNAILS_TABLE: ${ssm:/thumbgenai/thumbnails-table}
    THUMBNAIL_JOBS_TABLE: ${ssm:/thumbgenai/thumbnail-jobs-table}
    AWS_BUCKET_NAME: ${ssm:/thumbgenai/aws-bucket-name}
    AWS_CLOUDFRONT_DOMAIN: ${ssm:/thumbgenai/aws-cloudfront-domain}
    ACCESS_TOKEN_SECRET: ${ssm:/thumbgenai/access-token-secret}
    REFRESH_TOKEN_SECRET: ${ssm:/thumbgenai/refresh-token-secret}
    ACCESS_TOKEN_TTL: ${ssm:/thumbgenai/access-token-ttl}
    REFRESH_TOKEN_TTL: ${ssm:/thumbgenai/refresh-token-ttl}
    CORS_ORIGIN: ${ssm:/thumbgenai/cors-origin}
    VERTEX_AI_TIMEOUT_MS: ${ssm:/thumbgenai/vertex-ai-timeout-ms}
    GOOGLE_CLOUD_PROJECT: ${ssm:/thumbgenai/google-cloud-project}
    GOOGLE_CLOUD_LOCATION: ${ssm:/thumbgenai/google-cloud-location}
    GCP_SERVICE_ACCOUNT_KEY: ${ssm:/thumbgenai/gcp-service-account-key}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:TransactWriteItems
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${ssm:/thumbgenai/users-table}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${ssm:/thumbgenai/users-table}/index/email-index
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${ssm:/thumbgenai/sessions-table}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${ssm:/thumbgenai/sessions-table}/index/userId-index

package:
  patterns:
    - '!src/**'
    - '!test/**'
    - '!*.md'
    - '!*.mjs'
    - '!tsconfig*.json'
    - '!nest-cli.json'
    - 'dist/**'

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 5
    includeLayers: true # optional

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: GET
          path: /health

      - httpApi:
          method: POST
          path: /auth/register
      - httpApi:
          method: POST
          path: /auth/login
      - httpApi:
          method: POST
          path: /auth/logout
      - httpApi:
          method: POST
          path: /auth/refresh

      - httpApi:
          method: POST
          path: /thumbnails
      - httpApi:
          method: POST
          path: /thumbnails/{id}

      - httpApi:
          method: POST
          path: /s3/presigned-url
