import Image from 'next/image';
import Link from 'next/link';
import ArrowRightIcon from '@/components/icons/generated/ArrowRightIcon';

const galleryItems = [
  {
    title: 'Gaming Series',
    showTitle: true,
    alt: 'High-energy e-sports gaming thumbnail with vibrant purple neon lighting and dramatic central character silhouette',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyVsowerNCOWdpLAK9iknbnAsQAe8jlXg-wduPPWZRl59o34rarIZSI5VurNs5NwnFjwSIyyyRptYgw2UcrAYMsICBgYsfL0bC4L7Kyb7StiK4JyDajFpebQCGvGqQvWNFgFanxgVhuqpCMYjRsFIDoKjfVNgw52I8i382htEkgAFkK8zL1Z-G3B4eN_LvkB96aUZXRTXPAOp26N0B2vaNR_4bzvlZlRuLKKd19RKNc7OhLBQ2j1UF0dfsuSGlmYE7GqvolO89MuJA',
    className: 'col-span-2 aspect-video md:aspect-auto md:row-span-2',
    sizes: '(max-width: 768px) 100vw, 50vw',
  },
  {
    title: 'Lifestyle Workflow',
    showTitle: false,
    alt: 'Minimalist lifestyle thumbnail with clean typography and warm morning sunlight on a workspace',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLAodMvzfPxu0GsFbBpc4o6FYlIqB6YIeFrwtaeYpA5bzdjMFHLKbU0wSiB1YCB3_lF1r7W6Jnm-bTmWek3IQRVWbhMZhGwFibtffdt-ulYrqv_MiX66b_C0kB2KMyHHG06XtMlLYEs87YpCUHf8R86J4YEwnnii3HCD9sWUKtzABAFbnFFmLcQvpNYV2lMb0BEPDDmMOSt_K_e6Esy2P_23IbnkUdsec-BTRNvShp_YRoC8U04We4saBiV5CMjbE3ldM1v8pY9jcq',
    className: 'aspect-square',
    sizes: '(max-width: 768px) 50vw, 25vw',
  },
  {
    title: 'Tech Review',
    showTitle: false,
    alt: 'Tech review thumbnail with sharp focus on modern gadgets and futuristic electric blue highlights',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB1-_3-9h3QHNDrjrIz2QICcFg0Vzj3hv-3yDy57piNRmANjTXT17jMdbdDmGQ6eJqUSAMTAyDE6BHPvH5jGDFKvu1JOoaqGBtu730mstTehCmVfvTmQ-xDn6m0bGL_2BvpUcPwg7YTaZKkSs6-QuELERbVX3Bb1d_7PQKHwvuawwhvKveV1jjmQ6qS_u4B1fB4tdpaiEJyz4QvBHWHULNNdtxVn9kEFhZtsXFie1k6fqVpPoI8kpLewl80aSpsG9c8b2Capdv0tiNf',
    className: 'aspect-square',
    sizes: '(max-width: 768px) 50vw, 25vw',
  },
  {
    title: 'Creator Tutorial',
    showTitle: false,
    alt: 'Educational programming tutorial thumbnail with floating code snippets and professional dark mode aesthetic',
    src: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRwzvZL8ZL35dliUYAfYAHil-e_rJWp3eECFUdQ6j6HthITJwEcGyOKdJFyIRxPlS8lxlw7G8wsa0U2bHpV0qwoYsOD9Hel9eysaOaxcXmBcULSvIvRFVZqet1kKg3xuXliXWGenYfCp1m4iHkyQt0Aozis1tci4YnJiMDZs4Wiz9H1FUkxDgSNfCWnakmdZG55W6gABcrx9nveoq-AB9FWdCuGQd_6KpQfplFUHSv16qP55Bn2g0UckyGIfCopFFsnMhuofMgbFoi',
    className: 'col-span-2 aspect-video',
    sizes: '(max-width: 768px) 100vw, 50vw',
  },
];

export function GallerySection() {
  return (
    <section aria-labelledby="gallery-title" className="mx-auto max-w-7xl px-8 py-32">
      <div className="mb-16 flex flex-col gap-8 md:flex-row md:items-end md:justify-between">
        <div className="max-w-xl">
          <h2
            id="gallery-title"
            className="mb-4 font-headline text-4xl font-bold text-(--on-surface) md:text-5xl"
          >
            The Studio Gallery
          </h2>
          <p className="text-(--on-surface-variant)">
            Real thumbnails generated by creators using ThumbnailAI. No retouching required.
          </p>
        </div>

        <Link
          href="/thumbnails"
          className="inline-flex cursor-pointer items-center gap-2 font-bold text-(--primary) tonal-transition hover:gap-3"
        >
          View Thumbnails
          <ArrowRightIcon className="size-5" aria-hidden="true" />
        </Link>
      </div>

      <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
        {galleryItems.map((item) => (
          <article
            key={item.title}
            className={`group relative overflow-hidden rounded-3xl bg-(--surface-container) shadow-sm ${item.className}`}
          >
            <Image
              alt={item.alt}
              className="h-full w-full object-cover object-top transition-transform duration-500 group-hover:scale-110"
              fill
              src={item.src}
              sizes={item.sizes}
              priority={item.title === 'Gaming Series'}
            />
            {item.showTitle && (
              <div className="absolute inset-0 flex items-end bg-linear-to-t from-black/60 via-transparent to-transparent p-8 opacity-0 transition-opacity group-hover:opacity-100">
                <span className="font-headline text-xl font-bold text-white">{item.title}</span>
              </div>
            )}
          </article>
        ))}
      </div>
    </section>
  );
}
